### ISSUE TITLE
histogram, bins argument broken

### ISSUE THREAD

**Issue by roualdes** [roualdes/bplot#7]
The function `bp.histogram()` has an argument `bins`, which should be able to accept an int, specifying the number of bins.  However, the logic is broken.

**Comment by PJMenzies** [comment]
I'mma work on this. I'll see what I can do.

**Comment by roualdes** [comment]
I assigned you to this issue.

Notice that `bp.histogram()` is really just a wrapper around matplotlib's [`hist()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.hist.html).  The documentation for `hist()` suggests that `int`s are allowed.  So this is probably just an issue with bplot.

**Comment by PJMenzies** [comment]
I may be misunderstanding the problem, but the bins argument seems to work for me the way that matplotlib describes it.

![HistoBins](https://user-images.githubusercontent.com/37416360/66858014-5505d580-ef3d-11e9-9da9-8a8443cfe32d.png)

**Comment by roualdes** [comment]
Well, that's good.  Did I misremember the error/issue you found earlier?

**Comment by PJMenzies** [comment]
I asked you about bins in class and you said that they didn't work. I didn't actually test it until now.

**Comment by roualdes** [comment]
Apparently I messed something up cause you're right, it seems to work as it should.  Thanks for testing.  I'm going to close this.

Maybe you'd like to pick another issue to work on?
